routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('blade', 'Controller@blade');

Route::group(['middleware' => 'auth'], function() {

    Route::get('/shoppingLists/generate', 'ShoppingListsController@generate')->name('shoppingLists.generate');

    Route::resource('/shoppingLists', 'ShoppingListsController');
    Route::resource('/shoppingLists.products', 'ShoppingLists\ProductsController');

    Route::resource('/schedules', 'schedulesController');
});

app/schedule.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class schedule extends Model
{
    //
}

app/Http/Controllers/schedulesController.php
<?php

namespace App\Http\Controllers;

use App\schedule;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class schedulesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = Auth::user();

        return view('schedules.create')->withUser($user);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $user = Auth::user();

        return view('schedules.create')->withUser($user);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'product_name' => 'required',
            'buying_interval' => 'required|integer|min:1'
        ]);

        $user = Auth::user();

        $schedule = new schedule();
        $schedule->product_name = $request->product_name;
        $schedule->buying_interval = $request->buying_interval * 60 * 60 * 24;
        $user->schedules()->save($schedule);

        return view('schedules.create')->withUser($user);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        schedule::destroy($id);

        return view('schedules.create')->withUser(Auth::user());
    }
}

resources/views/schedules/create.blade.php
@extends('layouts.master')

@section('centered')
<div class="containerWhite">
    <div style="float:left;margin-left:4vh;margin-top:17vh;font-family: 'Montserrat', sans-serif;color:white;">
    <h2>New schedule:</h2>

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form method="post" action="{{ route('schedules.store') }}">
        {{ csrf_field() }}
        Product name: <input type="text" name="product_name" value="{{ old("product_name") }}">
        <br>
        <br>
        Buying interval in days: <input type="text" name="buying_interval" value="{{ old("buying_interval") }}">
        <br>
        <br>
        <input type="submit" value="Create">
    </form>
    </div>
    <div style="margin-left:78vh;margin-top:3vh;width:30%;font-family: 'Montserrat', sans-serif;color:#fff ">
    <h3>Current schedules:</h3>
    </div>
        <div style="float:left;height:65vh;background:white; margin-left: 26.3vh;width:24%;font-family: 'Montserrat', sans-serif;color:slategrey;-webkit-border-radius:2vh;overflow-y:auto">
    <ul>
        @foreach($user->schedules as $schedule)
            <li>
                <strong>{{ $schedule->product_name }} buy every: {{ $schedule->buying_interval / (60*60*24)}} day(s)</strong>

                {{ Form::open(['method' => 'DELETE', 'route' => ['schedules.destroy', $schedule->id]]) }}
                {{ Form::submit('Delete', ['class' => 'btn btn-danger']) }}
                {{ Form::close() }}
            </li>
        @endforeach
    </ul>
    </ul>
    </div>
</div>

</div>
@endsection